"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Play, Search, TriangleAlert } from "lucide-react";
import { WizardShell, type WizardStep } from "./wizard-shell";
import { WizardField } from "./field";

const steps: WizardStep[] = [
  {id:"scope",label:"Scope"},{id:"destination",label:"Destination"},{id:"providers",label:"Providers"},{id:"cutover",label:"Cutover"},{id:"preflight",label:"Preflight"},{id:"review",label:"Review"},{id:"migrate",label:"Migrate"},{id:"verify",label:"Verify"},
];

export function MigrationWizard() {
  const [step,setStep]=useState(0);
  const [application,setApplication]=useState("platform-tools");
  const [destination,setDestination]=useState("local");
  const [providerMode,setProviderMode]=useState("preserve");
  const [cutover,setCutover]=useState("readiness");
  const input="min-h-10 w-full rounded-md border border-[var(--border)] bg-[#0b1323] px-3 text-sm text-slate-200 outline-none focus:border-[var(--bh-signal-blue)] focus:ring-2 focus:ring-[var(--bh-signal-blue)]/25";
  return <WizardShell title="Migrate or replace deployment" description="Move an application or replace managed provider realizations without transferring authority away from BaseHarbor Core." steps={steps} currentStep={step} footer={<><button onClick={()=>setStep(v=>Math.max(0,v-1))} disabled={step===0} className="inline-flex min-h-10 items-center gap-2 px-3 text-xs text-slate-400 disabled:opacity-30"><ArrowLeft className="size-3.5" /> Back</button><div className="flex gap-2"><button className="min-h-10 px-3 text-xs text-slate-500">Cancel</button>{step<5&&<button onClick={()=>setStep(v=>v+1)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-ocean-blue)] px-4 text-xs text-white">Continue <ArrowRight className="size-3.5" /></button>}{step===5&&<><button className="inline-flex min-h-10 items-center gap-2 rounded-md border border-[var(--border)] px-4 text-xs text-slate-200"><Search className="size-3.5" /> Plan</button><button onClick={()=>setStep(6)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-harbor-orange)] px-4 text-xs text-white"><Play className="size-3.5" /> Preview migration<//button></>}{step===6&&<button onClick={()=>setStep(7)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-ocean-blue)] px-4 text-xs text-white">Verify <ArrowRight className="size-3.5" /></button>}</div></>}>
    {step===0&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Scope</h2><p className="mt-1 text-sm text-slate-500">Select the application/deployment whose realization should move or be replaced.</p></div><WizardField label="Application"><select value={application} onChange={e=>setApplication(e.target.value)} className={input}><option>platform-tools</option><option>demo</option></select></WizardField></div>}
    {step===1&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Destination</h2><p className="mt-1 text-sm text-slate-500">Choose an eligible target; Runtime Provider and Target Access remain independent.</p></div><WizardField label="Destination target"><select value={destination} onChange={e=>setDestination(e.target.value)} className={input}><option>local</option><option>lab</option></select></WizardField></div>}
    {step===2&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Providers</h2><p className="mt-1 text-sm text-slate-500">Decide whether existing provider bindings remain or managed realizations are replaced.</p></div><WizardField label="Provider strategy"><select value={providerMode} onChange={e=>setProviderMode(e.target.value)} className={input}><option value="preserve">Preserve compatible bindings</option><option value="replace">Replace managed realizations on destination</option></select></WizardField></div>}
    {step===3&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Cutover</h2><p className="mt-1 text-sm text-slate-500">Choose the semantic cutover condition, not low-level container timing.</p></div><WizardField label="Cutover condition"><select value={cutover} onChange={e=>setCutover(e.target.value)} className={input}><option value="readiness">Destination READY before source retirement</option><option value="maintenance">Explicit maintenance window</option></select></WizardField></div>}
    {step===4&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Preflight</h2><p className="mt-1 text-sm text-slate-500">Compatibility and recovery checks must pass before migration.</p></div><div className="divide-y divide-[var(--border)] rounded-md border border-[var(--border)]">{["Destination target eligible","Provider contracts compatible","Secrets/trust can be rebound","Recovery point available","Exposure/routing plan valid"].map(v=><div key={v} className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><CheckCircle2 className="size-4 text-emerald-400" />{v}</div>)}</div></div>}
    {step===5&&<div className="max-w-3xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Review</h2><p className="mt-1 text-sm text-slate-500">Review effective migration semantics and rollback protection.</p></div><div className="grid gap-6 md:grid-cols-2"><div className="space-y-4 rounded-md border border-[var(--border)] p-4">{[["Application",application],["Destination",destination],["Providers",providerMode],["Cutover",cutover]].map(([l,v])=><div key={l}><div className="text-[10px] uppercase text-slate-600">{l}</div><div className="mt-1 text-sm text-slate-200">{v}</div></div>)}</div><div className="rounded-md border border-[var(--border)] p-4 font-mono text-xs"><div className="text-emerald-300">+ realize destination deployment</div><div className="mt-2 text-amber-300">~ rebind providers/trust/routes</div><div className="mt-2 text-emerald-300">+ wait for READY</div><div className="mt-2 text-rose-300">- retire source realization after cutover</div></div></div><div className="flex gap-3 rounded-md border border-[var(--bh-harbor-orange)]/25 bg-[var(--bh-harbor-orange)]/[.035] p-4 text-xs text-orange-200"><TriangleAlert className="size-4 shrink-0" />Source retirement remains conditional on the selected cutover and recovery policy.</div></div>}
    {step===6&&<div className="flex min-h-[360px] flex-col items-center justify-center text-center"><Play className="size-8 text-[var(--bh-signal-blue)]" /><h2 className="mt-4 text-lg font-semibold text-white">Migration execution</h2><p className="mt-2 max-w-xl text-sm text-slate-500">BaseHarbor will reconcile the destination, perform cutover and retire the old realization under one evidenced execution.</p></div>}
    {step===7&&<div className="flex min-h-[360px] flex-col items-center justify-center text-center"><CheckCircle2 className="size-8 text-emerald-400" /><h2 className="mt-4 text-lg font-semibold text-white">Verification</h2><p className="mt-2 max-w-xl text-sm text-slate-500">Destination READY, providers and routes verified, source retirement completed according to plan.</p></div>}
  </WizardShell>;
}
