"use client";

import { WizardCancelButton } from "./cancel-button";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, KeyRound, Play, ShieldCheck, TriangleAlert } from "lucide-react";
import { WizardShell, type WizardStep } from "./wizard-shell";
import { WizardField } from "./field";

const steps: WizardStep[] = [
  { id:"target", label:"Target" },
  { id:"recovery", label:"Recovery material" },
  { id:"storage", label:"Storage" },
  { id:"preflight", label:"Preflight" },
  { id:"review", label:"Review" },
  { id:"recover", label:"Recover" },
  { id:"verify", label:"Verify" },
];

export function OpenBaoRecoveryWizard() {
  const [step,setStep]=useState(0);
  const [target,setTarget]=useState("local");
  const [recovery,setRecovery]=useState("~/.local/share/baseharbor-recovery/local/openbao-recovery.json");
  const input="min-h-10 w-full rounded-md border border-[var(--border)] bg-[#0b1323] px-3 text-sm text-slate-200 outline-none focus:border-[var(--bh-signal-blue)] focus:ring-2 focus:ring-[var(--bh-signal-blue)]/25";
  return <WizardShell title="Recover OpenBao" description="Recover managed OpenBao through BaseHarbor-owned recovery material and storage verification." steps={steps} currentStep={step} footer={<><button onClick={()=>setStep(v=>Math.max(0,v-1))} disabled={step===0} className="inline-flex min-h-10 items-center gap-2 px-3 text-xs text-slate-400 disabled:opacity-30"><ArrowLeft className="size-3.5" /> Back</button><div className="flex gap-2"><WizardCancelButton />{step<4&&<button onClick={()=>setStep(v=>v+1)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-ocean-blue)] px-4 text-xs text-white">Continue <ArrowRight className="size-3.5" /></button>}{step===4&&<button onClick={()=>setStep(5)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-harbor-orange)] px-4 text-xs text-white"><Play className="size-3.5" /> Preview recovery</button>}{step===5&&<button onClick={()=>setStep(6)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-ocean-blue)] px-4 text-xs text-white">Verify <ArrowRight className="size-3.5" /></button>}</div></>}>
    {step===0&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Target</h2><p className="mt-1 text-sm text-slate-500">Select the BaseHarbor target whose managed OpenBao instance requires recovery.</p></div><WizardField label="Target"><select value={target} onChange={e=>setTarget(e.target.value)} className={input}><option>local</option><option>lab</option></select></WizardField></div>}
    {step===1&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Recovery material</h2><p className="mt-1 text-sm text-slate-500">Use the configured BaseHarbor recovery file. Secret material is not copied into browser storage.</p></div><WizardField label="Recovery file" provenance="TargetDefinition.OpenBao.recovery-file"><input value={recovery} onChange={e=>setRecovery(e.target.value)} className={input} /></WizardField><div className="flex gap-3 rounded-md border border-[var(--border)] p-4 text-xs text-slate-500"><KeyRound className="size-4 shrink-0 text-[var(--bh-signal-blue)]" />Recovery material stays in the Core/target trust boundary.</div></div>}
    {step===2&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Storage</h2><p className="mt-1 text-sm text-slate-500">Verify shared PostgreSQL-backed OpenBao storage before recovery.</p></div><div className="divide-y divide-[var(--border)] rounded-md border border-[var(--border)]"><div className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><CheckCircle2 className="size-4 text-emerald-400" />Shared PostgreSQL reachable</div><div className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><CheckCircle2 className="size-4 text-emerald-400" />OpenBao database/user binding present</div><div className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><ShieldCheck className="size-4 text-emerald-400" />Native TLS trust valid</div></div></div>}
    {step===3&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Preflight</h2><p className="mt-1 text-sm text-slate-500">Recovery only proceeds when storage, identity and recovery material agree.</p></div><div className="divide-y divide-[var(--border)] rounded-md border border-[var(--border)]">{["Recovery material readable","Target identity matches","Storage backend compatible","TLS trust valid","No competing recovery execution"].map(v=><div key={v} className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><CheckCircle2 className="size-4 text-emerald-400" />{v}</div>)}</div></div>}
    {step===4&&<div className="max-w-3xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Review</h2><p className="mt-1 text-sm text-slate-500">Confirm recovery target, material and storage before mutation.</p></div><div className="grid gap-6 md:grid-cols-2"><div className="space-y-4 rounded-md border border-[var(--border)] p-4"><div><div className="text-[10px] uppercase text-slate-600">Target</div><div className="mt-1 text-sm text-slate-200">{target}</div></div><div><div className="text-[10px] uppercase text-slate-600">Recovery file</div><div className="mt-1 break-all font-mono text-xs text-slate-300">{recovery}</div></div><div><div className="text-[10px] uppercase text-slate-600">Storage</div><div className="mt-1 text-sm text-slate-200">shared PostgreSQL</div></div></div><div className="rounded-md border border-[var(--border)] p-4 font-mono text-xs"><div className="text-amber-300">~ stop/recover managed OpenBao</div><div className="mt-2 text-emerald-300">+ restore operational seal/recovery state</div><div className="mt-2 text-emerald-300">+ verify TLS/readiness</div></div></div><div className="flex gap-3 rounded-md border border-[var(--bh-harbor-orange)]/25 bg-[var(--bh-harbor-orange)]/[.035] p-4 text-xs text-orange-200"><TriangleAlert className="size-4 shrink-0" />Recovery changes a security-critical platform service and must remain evidenced and auditable.</div></div>}
    {step===5&&<div className="flex min-h-[360px] flex-col items-center justify-center text-center"><ShieldCheck className="size-8 text-[var(--bh-signal-blue)]" /><h2 className="mt-4 text-lg font-semibold text-white">Recovery execution</h2><p className="mt-2 max-w-xl text-sm text-slate-500">Core will perform the recovery and stream semantic progress under one execution identity.</p></div>}
    {step===6&&<div className="flex min-h-[360px] flex-col items-center justify-center text-center"><CheckCircle2 className="size-8 text-emerald-400" /><h2 className="mt-4 text-lg font-semibold text-white">Verification</h2><p className="mt-2 max-w-xl text-sm text-slate-500">OpenBao is READY, native TLS is valid and recovery evidence has been recorded.</p></div>}
  </WizardShell>;
}

