import { ContractPendingButton } from "@/components/ui/contract-pending";
import { WizardCancelButton } from "./cancel-button";
"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Play, Search } from "lucide-react";
import { WizardShell, type WizardStep } from "./wizard-shell";
import { WizardField } from "./field";

const steps: WizardStep[] = [
  {id:"organization",label:"Organization"},{id:"environments",label:"Environments"},{id:"defaults",label:"Defaults"},{id:"security",label:"Security policy"},{id:"review",label:"Review"},
];

export function PlatformOnboardingWizard() {
  const [step,setStep]=useState(0);
  const [organization,setOrganization]=useState("default");
  const [domain,setDomain]=useState("baseharbor.localhost");
  const input="min-h-10 w-full rounded-md border border-[var(--border)] bg-[#0b1323] px-3 text-sm text-slate-200 outline-none focus:border-[var(--bh-signal-blue)] focus:ring-2 focus:ring-[var(--bh-signal-blue)]/25";
  return <WizardShell title="Platform onboarding" description="Establish organization defaults and policy provenance without contaminating portable Application Intent." steps={steps} currentStep={step} footer={<><button onClick={()=>setStep(v=>Math.max(0,v-1))} disabled={step===0} className="inline-flex min-h-10 items-center gap-2 px-3 text-xs text-slate-400 disabled:opacity-30"><ArrowLeft className="size-3.5" /> Back</button><div className="flex gap-2"><WizardCancelButton />{step<4?<button onClick={()=>setStep(v=>v+1)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[var(--bh-ocean-blue)] px-4 text-xs text-white">Continue <ArrowRight className="size-3.5" /></button>:<><ContractPendingButton issue="#767/#770"><Search className="size-3.5" /> Validate</ContractPendingButton><ContractPendingButton issue="#767/#770"><Play className="size-3.5" /> Apply platform defaults</ContractPendingButton></>}</div></>}>
    {step===0&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Organization</h2><p className="mt-1 text-sm text-slate-500">Define the source for organization-scoped defaults and policy.</p></div><WizardField label="Organization name"><input value={organization} onChange={e=>setOrganization(e.target.value)} className={input} /></WizardField></div>}
    {step===1&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Environment conventions</h2><p className="mt-1 text-sm text-slate-500">Establish dev/test/prod conventions and inherited defaults.</p></div><div className="divide-y divide-[var(--border)] rounded-md border border-[var(--border)]">{["dev — trusted local operator","test — managed OIDC / policy","prod — managed OIDC / strict policy"].map(v=><div key={v} className="px-4 py-3 text-sm text-slate-300">{v}</div>)}</div></div>}
    {step===2&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Defaults</h2><p className="mt-1 text-sm text-slate-500">Defaults remain provenance-aware and overridable only where policy permits.</p></div><WizardField label="Development domain" provenance="organization default"><input value={domain} onChange={e=>setDomain(e.target.value)} className={input} /></WizardField><div className="rounded-md border border-[var(--border)] p-4 text-xs text-slate-500">PostgreSQL scope: shared · Default dev target: local · Observability: metrics/logs/traces recommended</div></div>}
    {step===3&&<div className="max-w-2xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Security policy</h2><p className="mt-1 text-sm text-slate-500">Policy controls are visible and locked where the platform mandates them.</p></div><div className="divide-y divide-[var(--border)] rounded-md border border-[var(--border)]">{["TLS required for managed access","test/prod require authenticated operator identity","destructive operations require Core confirmation policy","secret material remains outside Console persistence"].map(v=><div key={v} className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><CheckCircle2 className="size-4 text-emerald-400" />{v}</div>)}</div></div>}
    {step===4&&<div className="max-w-3xl space-y-6"><div><h2 className="text-lg font-semibold text-white">Review</h2><p className="mt-1 text-sm text-slate-500">Review organization defaults and policy provenance before publishing them.</p></div><div className="grid gap-6 md:grid-cols-2"><div className="space-y-4 rounded-md border border-[var(--border)] p-4"><div><div className="text-[10px] uppercase text-slate-600">Organization</div><div className="mt-1 text-sm text-slate-200">{organization}</div></div><div><div className="text-[10px] uppercase text-slate-600">Development domain</div><div className="mt-1 text-sm text-slate-200">{domain}</div></div><div><div className="text-[10px] uppercase text-slate-600">Environment model</div><div className="mt-1 text-sm text-slate-200">dev / test / prod</div></div></div><div className="rounded-md border border-[var(--border)] p-4 font-mono text-xs"><div className="text-emerald-300">+ organization defaults</div><div className="mt-2 text-emerald-300">+ environment conventions</div><div className="mt-2 text-emerald-300">+ security policy constraints</div><div className="mt-2 text-sky-300">= provenance retained for effective values</div></div></div></div>}
  </WizardShell>;
}
